### ISSUE TITLE
Cannot find txt_dataset_json_path

### ISSUE THREAD

**Issue by jiyt17** [WebQnA/WebQA_Baseline#3]
Thank you for your contribution on baseline.
I took part in WebQA competition, which provides data files including WebQA_train_val.json, WebQA_test.json, imgs and so on. But I can't find txt_dataset_json_path, img_dataset_json_path files which run_webqa.py needs.

**Comment by fireflycsq** [comment]
me too

**Comment by zdxdsw** [comment]
For path issues, please also refer to this [README](https://github.com/WebQnA/WebQA_Baseline/blob/main/README.md#news) and issue [#7](https://github.com/WebQnA/WebQA_Baseline/issues/7).
