### ISSUE TITLE
Path issues & Missing files and folders

### ISSUE THREAD

**Issue by soundarya98** [WebQnA/WebQA_Baseline#6]
Thank you so much for this repository!

Meta comment: most of the paths are absolute and specific to the author's computer. 
Please provide some clarifications on the following paths:
1. txt_dataset_json_path
2. img_dataset_json_path
3. gold_feature_folder
4. distractor_feature_folder
5. x_distractor_feature_folder

**Comment by zdxdsw** [comment]
Thanks for asking! We have clarified what those arguments are in our [README](https://github.com/WebQnA/WebQA_Baseline/blob/main/README.md#news). 

We explain again here: 

In our baseline code, we separate the data loading of image- and text-based queries for the sake of performance breakdown. Thus, the two arguments, `txt_dataset_json_path` and `img_dataset_json_path`, correspond to the two folds,  according to the `Qcate` field. 

Next, we explain what arguments `--gold_feature_folder`, `--distractor_feature_folder`, and `--x_distractor_feature_folder` are. Basically, during implementation we divide the images into 3 buckets: positive images for image-based queries (`gold`), negative images for image-based queries (`distractors`) and negative images for text-based queries (`x_distractors`), where the 'x' stands for 'cross-modality'. Image- and text-based queries can be disinguished via the "Qcate" field in the dataset file. Text-based queries all have `Qcate == 'text'`, while the rest are image-based ones.

We're happy to address any further concerns.

**Comment by soundarya98** [comment]
Thank you for the clarification! Closing issue now.
