### ISSUE TITLE
pytorch_pretrained_bert loading and path issues

### ISSUE THREAD

**Issue by Deep-Karkhanis** [WebQnA/WebQA_Baseline#7]
Thanks a lot for the novel dataset and baselines!

The repository doesn't seem to be plug and play. The specialized bert model used here seems to not be loaded correctly by the `run_webqa.py` file.
Moving `run_webqa.py` one level up from the `vlp/` folder seems to fix some but not all path issues. Most paths given in the file seem to be absolute paths and corresponding files and folders are missing from the repository

**Comment by zdxdsw** [comment]
Thanks for asking! Please see our [README](https://github.com/WebQnA/WebQA_Baseline/blob/main/README.md#news) for explanations of absolute path arguments. Let us know if there are still unclear arguments.

If you're having trouble import BERT model classes, please try `sys.path.append("path to ./VLP")`

Hope that helps!

**Comment by zdxdsw** [comment]
Hi!
I just want to follow up to see if my previous answer addressed your problem. If yes, I will close the issue. Otherwise, I'm happy to address any follow-up questions!
